version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.19-1.1.15-aarch64
    container_name: mysql-count_of_money
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: count_of_money
      MYSQL_DATABASE: count_of_money
      MYSQL_USER: count_of_money
      MYSQL_PASSWORD: count_of_money

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"


  express:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
