version: '3'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql-count_of_money
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: count_of_money
      MYSQL_DATABASE: count_of_money
      MYSQL_USER: count_of_money
      MYSQL_PASSWORD: count_of_money

  express:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"

  react:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"  # Use port 80 for the React service's Nginx
